# Generated by Django 4.1.3 on 2022-11-27 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinyl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(upload_to='vinyls')),
                ('extra_pic1', models.ImageField(blank=True, null=True, upload_to='vinyls')),
                ('extra_pic2', models.ImageField(blank=True, null=True, upload_to='vinyls')),
                ('extra_pic3', models.ImageField(blank=True, null=True, upload_to='vinyls')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('vinyl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='vinyl.vinyl')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('vinyl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='vinyl.vinyl')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('vinyl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vinyl.vinyl')),
            ],
        ),
    ]
